name: lint

on: [ push ]

jobs:
  lint-check:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Check init.sh
      run: shellcheck ${GITHUB_WORKSPACE}/init.sh
    - name: Check langconf.sh
      run: shellcheck ${GITHUB_WORKSPACE}/langconf.sh