name: CI

on: [ push ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run init.sh
      run: bash init.sh
    - name: Run brew bundle
      run: brew bundle --global